# Generated by Django 2.2.2 on 2019-06-09 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CSDNBlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=100)),
                ('writer', models.CharField(max_length=30)),
                ('writer_id', models.CharField(max_length=30)),
                ('read_count', models.IntegerField()),
                ('content', models.TextField()),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=100)),
                ('date', models.DateTimeField(verbose_name='date searched')),
            ],
        ),
    ]
